---
- name: Reboot server
  shell: 'sleep 5 && reboot'
  async: 1
  poll: 0
  listen: reboot
  when:
    - test | default('false') == 'false'

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  listen: wait_for_reboot
  when:
    - test | default('false') == 'false'
