---
- include: environment.yml
- include: root_certificate.yml
  when:
    - '"proxy" in base'
    - '"root_certificate" in base.proxy'
    - 'base.proxy.root_certificate'
- include: python.yml
- include: hostname.yml
  when:
    - '"hostname" in base'
    - 'base.hostname'
- include: ntp.yml
  when:
    - '"ntp" in base'
    - 'base.ntp'
- include: filesystem.yml
- include: security.yml
  when:
    - '"disable_security" in base'
    - 'base.disable_security'
- include: certs.yml
- include: docker.yml
- include: docker_registry.yml
  when: inventory_hostname in groups['docker_registry']
- include: custom-docker_registry.yml
  when:
    - '"docker_registry" in base'
