---
- name: Install NTP
  yum:
    name: ntp
    state: present

- name: Copy ntp.conf file
  template:
    src: templates/ntp.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: start ntp
