---
- name: Check if firewalld exist
  stat:
    path: /etc/init.d/firewalld
  register: service_status

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Check if ip6tables exist
  stat:
    path: /etc/init.d/ip6tables
  register: service_status

- name: Stop and disable ip6tables
  service:
    name: ip6tables
    state: stopped
    enabled: no
  when: service_status.stat.exists

- name: Disable SELinux
  selinux:
    state: disabled
  notify:
    - reboot
    - wait_for_reboot
